"""initial schema

Revision ID: 8c872b9f6bda
Revises: 
Create Date: 2026-06-26 13:52:10.595253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c872b9f6bda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('etf_pool', sa.JSON(), nullable=False),
    sa.Column('momentum_window', sa.Integer(), nullable=False),
    sa.Column('rebalance_freq', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_created_at'), 'backtest_runs', ['created_at'], unique=False)
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'date', name='uq_daily_prices_code_date')
    )
    op.create_index('ix_daily_prices_code', 'daily_prices', ['code'], unique=False)
    op.create_table('etfs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=2), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etfs_category'), 'etfs', ['category'], unique=False)
    op.create_index(op.f('ix_etfs_code'), 'etfs', ['code'], unique=True)
    op.create_table('signal_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('etf_code', sa.String(length=10), nullable=False),
    sa.Column('momentum_score', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'etf_code', name='uq_signal_snapshots_date_etf')
    )
    op.create_index('ix_signal_snapshots_date', 'signal_snapshots', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_snapshots_date', table_name='signal_snapshots')
    op.drop_table('signal_snapshots')
    op.drop_index(op.f('ix_etfs_code'), table_name='etfs')
    op.drop_index(op.f('ix_etfs_category'), table_name='etfs')
    op.drop_table('etfs')
    op.drop_index('ix_daily_prices_code', table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_backtest_runs_created_at'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
